language: android
jdk: oraclejdk8
dist: trusty
android:
  components:
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-29.0.0-rc3

    # The SDK version used to compile your project
    - android-28

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
before_install:
  - chmod +x gradlew
  - touch $HOME/.android/repositories.cfg
  - yes | sdkmanager "platforms;android-28"
  - yes | sdkmanager "build-tools;28.0.3"
before_script:
  - ./gradlew clean
script:
  - ./gradlew build check